Repository errbotio/errbot, pull requests merged in 2019-04, with the labels that each got.

#1316 Fixes #1312 - errbot -l crashes
  errbot/backend_plugin_manager.py
  errbot/cli.py
Labels: in progress

#1311 Make --storage-merge merge configs, not overwrite
  errbot/cli.py
Labels: in progress

#1310 Fix storage development docs
  docs/user_guide/storage_development/index.rst
Labels: in progress

#1296 Move to python git rather than system git
  errbot/core_plugins/help.py
  errbot/repo_manager.py
  errbot/utils.py
  setup.py
Labels: in progress

#1317 fix: Remove waffle
  README.rst
Labels: type: documentation

#1328 fix: backup command exporting plugin values
  errbot/core_plugins/backup.py
Labels: #plugins, type: bug
