Repository errbotio/errbot, pull requests merged in 2020-10, with the labels that each got.

#1456 fix: Add missing email property to backends
  errbot/backends/irc.py
  errbot/backends/slack_rtm.py
  errbot/backends/text.py
  errbot/backends/xmpp.py
Labels: #backend, #tests, type: bug

#1455 chore: Add github actions
  .github/workflows/python-package.yml
Labels: #deployment, #tests, type: support/question

#1461 fix: Set email property as non-abstract
  errbot/backends/base.py
Labels: #backend, #needs_validation, #regression, type: bug

#1458 fix: username to userid method signature
  errbot/backends/base.py
  errbot/backends/slack_rtm.py
Labels: #Slack, #backend

#1467 fix: AttributeError in callback_reaction
  errbot/backends/base.py
Labels: type: bug

#1471 docs: fix webhook examples
  docs/user_guide/plugin_development/webhooks.rst
Labels: type: documentation

#1470 fix: merging configs via cli with unknown keys
  errbot/cli.py
Labels: #regression, backend: Common

#1462 Fix error when plugin plug file is missing description
  errbot/core_plugins/help.py
Labels: feature: Formatting
