Repository errbotio/errbot, pull requests merged in 2020-11, with the labels that each got.

#1474 refactor: Split changelog by major versions
  CHANGES-4x.rst
  CHANGES-5x.rst
  CHANGES.rst
  setup.py
Labels: #packaging, #release-process

#1464 Allow dependabot to check GitHub actions weekly
  .github/dependabot.yml
Labels: #release-process

#1477 Enable testing using Python 3.9
  .github/workflows/python-package.yml
  .travis.yml
  CHANGES.rst
  setup.py
  tox.ini
Labels: #release-process

#1478 Remove travis configuration
  .github/workflows/python-package.yml
  .travis.yml
  README.rst
  setup.cfg
  tests/config-ci.py
Labels: #release-process

#1465 Chore: minor code cleanup
  errbot/backends/base.py
  errbot/backends/graphic.py
  errbot/backends/hipchat.py
  errbot/backends/null.py
  errbot/backends/slack.py
  errbot/backends/slack_rtm.py
  errbot/backends/telegram_messenger.py
  errbot/backends/test.py
  errbot/backends/xmpp.py
  errbot/bootstrap.py
  errbot/botplugin.py
  errbot/cli.py
  errbot/core_plugins/help.py
  errbot/core_plugins/vcheck.py
  errbot/core_plugins/webserver.py
  errbot/flow.py
  errbot/plugin_manager.py
  errbot/rendering/__init__.py
  errbot/rendering/ansiext.py
  errbot/repo_manager.py
  errbot/storage/base.py
  errbot/streaming.py
  errbot/templating.py
  errbot/utils.py
  tools/plugin-gen.py
Labels: feature: Formatting
