Repository errbotio/errbot, pull requests merged in 2021-01, with the labels that each got.

#1497 Remove Google+ References
  CHANGES.rst
  README.rst
Labels: type: documentation

#1496 Split the command on _all_ whitespace when matching commands
  CHANGES.rst
  errbot/core.py
Labels: backend: Common, type: bug

#1459 fix: whoami formatting
  CHANGES.rst
  errbot/core_plugins/utils.py
Labels: feature: Formatting, type: bug
